apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: authservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: authcontainer
          image: linnytv/authservice:latest
          ports:
            - containerPort: 5000
