apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: productservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: productscontainer
          image: linnytv/productservice:latest 
          ports:
            - containerPort: 3001